name: C

on:
  push:
    branches: [ "**" ]
    paths:
      - c/**
      - .github/workflows/c.yaml
  pull_request:
    branches: [ "**" ]
    paths:
      - c/**
      - .github/workflows/c.yaml

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: c

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Xmake
      uses: xmake-io/github-action-setup-xmake@v1
      with:
        xmake-version: latest
        actions-cache-folder: '.xmake-cache'
        build-cache: true

    - name: Run lint
      run: xmake lint

    - name: Run test
      run: xmake test:all
